config/routes.rb
Rails.application.routes.draw do   devise_for :users
  root "users#show"
  resources :users, only: %i[show] do
    get 'posts', to: 'users#posts'
    get 'groups', to: 'users#groups'
    resources :groups do
      get 'join', to: 'groups#join'
      get 'leave', to: 'groups#leave'
      resources :posts do
        resources :comments, only: %i[create destroy]
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: {message: "Group name can't be blank"}
  belongs_to :user
  has_many :user_groups
  has_many :posts
  def members_count
    self.user_groups.count
  end
  def posts_count
    self.posts.count
  end
  def last_active
    active_days=(Time.now-self.updated_at.to_time)/1.day
    if active_days < 0.1
      active_days=(active_days*24*24).round(2).to_i.to_s+" minutes"
    elsif active_days  < 1
      active_days=(active_days*24).round(2).to_i.to_s+" hours"
    else
    return active_days.round(2).to_i.to_s+" days"
    end
    active_days
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  def join
    @group = Group.find(params[:group_id])
    join=UserGroup.new(user: current_user, group: @group)
    respond_to do |format|
      if join.save
        format.html { redirect_to user_path(@group) }
        format.turbo_stream {
        render turbo_stream: turbo_stream.replace(
          @group, GroupComponent.new(group: @group).render_in(view_context))
      }
      else
        format.html { redirect_to user_path(current_user), notice: "Server is expecting turbo streams hence a SPA"}
      end
    end
  end

    def leave
      if params[:member_id]
        # only an admin of the group can remove a member
        group = Group.find(params[:group_id])
        member=User.find(params[:member_id])
        if can? :update, group
          join=UserGroup.find_by(user: member, group: group)
          join.destroy
          respond_to do |format|
            format.turbo_stream {
              render turbo_stream: turbo_stream.remove(member)
            }
          end
        end
            return
      end
      #everyone can leave a group they are a member of
    @group = Group.find(params[:group_id])
    join=UserGroup.find_by(user: current_user, group: @group)
    respond_to do |format|
      if join.destroy
        format.html { redirect_to user_path(@group) }
        format.turbo_stream {
        render turbo_stream: turbo_stream.replace(
          @group, GroupComponent.new(group: @group).render_in(view_context))
      }
      else
        format.html { redirect_to user_path(current_user), notice: "Server is expecting turbo streams hence a SPA"}
      end
    end
  end

  def new
    p request.original_url
     respond_to do |format|
        format.turbo_stream {
        render turbo_stream: turbo_stream.prepend(
          "new_group", NewGroupComponent.new(group: Group.new).render_in(view_context))
      }
        format.html { redirect_to user_path(current_user), notice: "Server is expecting turbo streams hence a SPA"}
      end
  end

  def edit
     respond_to do |format|
        format.turbo_stream {
        render turbo_stream: turbo_stream.prepend(
          @group, NewGroupComponent.new(group: @group).render_in(view_context))
      }
        format.html { redirect_to user_path(current_user), notice: "Server is expecting turbo streams hence a SPA"}
      end
  end

  def create
    group = Group.new(user: current_user,name: group_params[:name])
    respond_to do |format|
      if group.save!
        UserGroup.create!(user: current_user, group: group)
      end
        format.html { redirect_to user_path(current_user), notice: "Server is expecting turbo streams hence a SPA" }
        format.turbo_stream {
        render turbo_stream: turbo_stream.prepend(
          'groups', GroupComponent.new(group: group).render_in(view_context))
      }
    end
  end
  def update
    # server side authorization
    unless current_user.is_admin?(@group)
      redirect_to user_path(current_user), notice: "You are not authorized to update this group"
      return
    end
    respond_to do |format|
      if @group.update(user: current_user, name: group_params[:name])
        format.turbo_stream {
        render turbo_stream: turbo_stream.replace(
          @group, GroupComponent.new(group: @group).render_in(view_context))
      }
      else
        format.html { redirect_to user_path(current_user), notice: "Server is expecting turbo streams hence a SPA"}
      end
    end
  end

  def destroy
    # server side authorization
    unless current_user.is_admin?(@group)
      redirect_to user_path(current_user), notice: "You are not authorized to delete this group"
      return
    end
    @group.user_groups.destroy_all
    @group.posts.destroy_all
    @group.destroy

    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.remove(@group)
      }
      format.html { redirect_to user_path(current_user), notice: "Server is expecting turbo streams hence a SPA"}
    end
  end

  private

    def set_group
      @group = Group.find(params[:id])
    end


    def group_params
      param=params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, class: "contents", url: user_group_path(group)) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= group.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= group.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= group.body %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this group", group, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this group', edit_group_path(group), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/groups/_index.html.erb
<div class="">
  <%url=request.base_url.slice(0,request.original_url.length-1) %>
<h1 class="title">Groups</h1>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="heading flex justify-between border-b-4 border-sky-500 pb-4 mb-4">
    <div class=" inline p-3">
      <%= link_to raw('<i class="fa-solid fa-filter-circle-xmark m-1"></i>All Group'), user_groups_path(current_user), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline md:p-3", data: {turbo_stream: ""} %>
      <%= link_to raw('<i class="fa-solid fa-spa m-1"></i>Created by me'), user_groups_path(current_user, filter: "mine"), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline md:p-3", data: {turbo_stream: ""} %>
      <%= link_to raw('<i class="fa-solid fa-landmark-dome m-1"></i>Where I\'m a member'), user_groups_path(current_user, filter: "member"), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline md:p-3", data: {turbo_stream: ""} %>
    </div>
    <div data-controller="modal" id="new_group" data-modal-target="url" value="
    <%=url+new_user_group_path(user_id: current_user.id)%>">
      <button href="" class="overlay-btn blue"
       data-action="modal#renderGroupForm">
        <i class="fa-solid fa-plus"></i> Create Group
      </button>
    </div>
  </div>

  <div id="groups" class="min-w-full">

      <%= render(GroupComponent.with_collection(@groups)) %>
      <%# <%= render(GroupComponent.new(group: @groups.first)) %>
  </div>
</div>

app/views/groups/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing group</h1>

  <%= render "form", group: @group %>

  <%= link_to "Show this group", @group, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to groups", groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>
 

app/views/groups/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Groups</h1>
    <%= link_to 'New group', new_group_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="groups" class="min-w-full">
    <%= render @groups %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New group</h1>

  <%= render "form", group: @group %>

  <%= link_to 'Back to groups', user_groups_path(id: current_user.id), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/groups/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @group %>

    <%= link_to 'Edit this group', edit_group_path(@group), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this group', group_path(@group), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to groups', groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>