config/routes.rb
Rails.application.routes.draw do   devise_for :users
  root "users#show"
  resources :users, only: %i[show] do
    get 'posts', to: 'users#posts'
    get 'groups', to: 'users#groups'
    resources :groups do
      get 'join', to: 'groups#join'
      get 'leave', to: 'groups#leave'
      resources :posts do
        resources :comments, only: %i[create destroy]
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: {message: "Post title can't be blank"}
  validates :body, presence: {message: "Post body can't be blank"}
  belongs_to :user
  belongs_to :group
  has_many :comments, as: :contents
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:destroy, :update, :show]
  before_action :param_filter, only: [:create]

  def show
    respond_to do |format|
        format.turbo_stream {
        render turbo_stream: turbo_stream.update(
          'active-content', ShowPostComponent.new(post: @post).render_in(view_context))
      }
        format.html { redirect_to user_path(current_user), notice: "Server is expecting turbo streams hence a SPA" }
      end
  end

  def update
    # server side authorization
    unless can? :update, @post || current_user.is_admin?(@post.group)
      redirect_to user_path(current_user), notice: "You are not authorized to update this post"
      return
    end
    respond_to do |format|
      if @post.update(param_filter)
        format.turbo_stream {
        render turbo_stream: turbo_stream.update(
          'active-content', ShowPostComponent.new(post: @post).render_in(view_context))
      }
        format.html { redirect_to user_path(current_user), notice: "Server is expecting turbo streams hence a SPA" }
      end
    end
  end

  def destroy
    # server side authorization
    unless can? :update, @post || current_user.is_admin?(@post.group)
      redirect_to user_path(current_user), notice: "You are not authorized to delete this post"
      return
    end
    @post.comments.destroy_all
    @post.destroy
    redirect_to user_path(current_user)
  end

  def create
        post = Post.new(title: param_filter[:title],body: param_filter[:body],user_id: params[:user_id],
          group_id: params[:group_id])
    respond_to do |format|
      if post.save!
        format.turbo_stream {
        render turbo_stream: turbo_stream.prepend(
          'posts', PostComponent.new(post: post).render_in(view_context))
      }
        format.html { redirect_to user_path(current_user), notice: "Server is expecting turbo streams hence a SPA" }
      end
    end
  end
  private
  def set_post
    @post=Post.includes(:user, :group).find(params[:id])
  end
  def param_filter
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_index.html.erb
<div class="grid grid-cols-3 gap-4">
  <div class="col-span-2">
    <% if current_user.joined?(@group) %>
    <div id="new_post">
      <%= render(NewPostComponent.new(post: Post.new)) %>
    </div>
    <% end %>
    <h1 class="title">All posts</h1>
    <div id="posts" class="min-w-full">
      <%= render(PostComponent.with_collection(@posts)) %>
    </div>
</div>
<div id="group_members" class="p">
  <h2 class="text-xl"> Members </h2>
  <%@group.user_groups.each do |member|%>
  <div id="<%= dom_id member.user%>">
  <%= member.user.email%>
<%# oly the members can be removed (group admin cannot leave the group but can delete the group itself) %>
    <% if (can? :manage, @group )&& (!member.user.is_admin?(@group))%>
      <%= link_to raw('<i class="fa-regular fa-circle-xmark text-red-600"></i>'), user_group_leave_path(member_id: member.user.id, group_id: @group.id), data: {turbo_stream: ""}  %>
    <% end %>
 </div>
  <% end %>
</div>

</div>